"""Fix build-pages.py and index.html to use BASE_HREF for GitHub Pages subdirectory."""
import re, os

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(ROOT)

# ─── Patch build-pages.py ───────────────────────────────────────────────────

bp = os.path.join(ROOT, 'build-pages.py')
with open(bp, 'r', encoding='utf-8') as f:
    c = f.read()

# 1. Add BASE_HREF constant after ROOT line
c = c.replace(
    "ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))",
    "ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))\n\n"
    "# /wallenvy/  -> GitHub Pages subdirectory (djtaylor333.github.io/wallenvy/)\n"
    "# /           -> Custom domain root (wallenvy.com.au) — change when going live\n"
    "BASE_HREF = '/wallenvy/'"
)

# 2. Update page() function — add <base>, strip leading / from asset paths
c = c.replace(
    '  <link rel="icon" href="/assets/images/favicon.svg" type="image/svg+xml">\n'
    '  <link rel="stylesheet" href="/assets/css/style.css">\n'
    '  {THEME_SCRIPT}\n'
    '</head>',
    '  <base href="{BASE_HREF}">\n'
    '  <link rel="icon" href="assets/images/favicon.svg" type="image/svg+xml">\n'
    '  <link rel="stylesheet" href="assets/css/style.css">\n'
    '  {THEME_SCRIPT}\n'
    '</head>'
)

# 3. Strip leading / from <script src>
c = c.replace('<script src="/assets/js/main.js">', '<script src="assets/js/main.js">')

# 4. Make NAV home links relative
c = c.replace('href="/" class="nav-logo"', 'href="./" class="nav-logo"')
c = c.replace(
    'href="/" class="nav-link" data-path="/"',
    'href="./" class="nav-link" data-path="/"'
)

# 5. Strip leading / from all internal .html hrefs in nav+footer
c = re.sub(r'href="/([a-z][^"]*\.html)"', r'href="\1"', c)

# 6. Make FOOTER home link relative
c = c.replace('href="/" class="footer-logo"', 'href="./" class="footer-logo"')

with open(bp, 'w', encoding='utf-8') as f:
    f.write(c)
print("build-pages.py patched")

# ─── Verify ─────────────────────────────────────────────────────────────────

checks = [
    ("BASE_HREF var",            "BASE_HREF = '/wallenvy/'" in c),
    ("<base href= in page()",    '<base href="{BASE_HREF}">' in c),
    ("assets/css no leading /",  'href="assets/css/style.css"' in c),
    ("assets/js no leading /",   'src="assets/js/main.js"' in c),
    ("favicon rel",              'href="assets/images/favicon.svg"' in c),
    ("nav home relative",        'href="./" class="nav-logo"' in c),
    ("nav services relative",    'href="services.html"' in c),
    ("footer logo relative",     'href="./" class="footer-logo"' in c),
]
for label, ok in checks:
    print(f"  [{'ok' if ok else 'FAIL'}] {label}")

# ─── Patch index.html (not generated by build script) ───────────────────────

idx = os.path.join(REPO, 'index.html')
with open(idx, 'r', encoding='utf-8') as f:
    ih = f.read()

# Insert <base href> before <link rel="stylesheet">
ih = ih.replace(
    '  <link rel="stylesheet" href="/assets/css/style.css">',
    '  <base href="/wallenvy/">\n  <link rel="stylesheet" href="assets/css/style.css">'
)
ih = ih.replace('href="/assets/images/favicon.svg"', 'href="assets/images/favicon.svg"')
ih = ih.replace('src="/assets/js/main.js"', 'src="assets/js/main.js"')

# Nav home links
ih = ih.replace('href="/" class="nav-logo"', 'href="./" class="nav-logo"')
ih = ih.replace('href="/" class="nav-link" data-path="/"', 'href="./" class="nav-link" data-path="/"')
ih = re.sub(r'href="/([a-z][^"]*\.html)"', r'href="\1"', ih)
ih = ih.replace('href="/" class="footer-logo"', 'href="./" class="footer-logo"')

# Hero project images
ih = ih.replace('src="/assets/images/', 'src="assets/images/')

with open(idx, 'w', encoding='utf-8') as f:
    f.write(ih)
print("index.html patched")
